# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6274, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

import msrest.serialization


class ApiResponse(msrest.serialization.Model):
    """ApiResponse.

    :param code:
    :type code: int
    :param type:
    :type type: str
    :param message:
    :type message: str
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'type': {'key': 'type', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(ApiResponse, self).__init__(**kwargs)
        self.code = kwargs.get('code', None)
        self.type = kwargs.get('type', None)
        self.message = kwargs.get('message', None)


class Product(msrest.serialization.Model):
    """Product.

    :param id:
    :type id: long
    :param name:
    :type name: str
    :param inventory_count:
    :type inventory_count: int
    :param cost_per_unit:
    :type cost_per_unit: float
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'long'},
        'name': {'key': 'name', 'type': 'str'},
        'inventory_count': {'key': 'inventoryCount', 'type': 'int'},
        'cost_per_unit': {'key': 'costPerUnit', 'type': 'float'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(Product, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.name = kwargs.get('name', None)
        self.inventory_count = kwargs.get('inventory_count', None)
        self.cost_per_unit = kwargs.get('cost_per_unit', None)
