# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6274, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum

class HostOptions(str, Enum):
    """choices for server host
    """

    https_virtserver_swaggerhub_com_store_api_v1_0_0 = "https://virtserver.swaggerhub.com/store/api/v1.0.0"  #: host: https://virtserver.swaggerhub.com/store/api/v1.0.0.
    http_virtserver_swaggerhub_com_store_api_v1_0_0 = "http://virtserver.swaggerhub.com/store/api/v1.0.0"  #: host: http://virtserver.swaggerhub.com/store/api/v1.0.0.
