# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6274, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

import logging

from azure.functions import HttpRequest, HttpResponse

from .. import models

def main(req: HttpRequest) -> HttpResponse:
    """add_product operations.

    - Auto-generated function code

    :param req: Passing the request
    :type req: HttpRequest
    :returns: Request
    :rtype: HttpResponse
    """

    logging.info('Python HTTP trigger function processed a request.')

    try:
        ### Do Magic Here! ###

        return HttpResponse(u"Return stuff here.", status_code=200)

    except:
        return HttpResponse(u"This function executed unsuccessfully.",
                                 status_code=405)
