# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6274, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import ApiResponse
    from ._models_py3 import Product
except (SyntaxError, ImportError):
    from ._models import ApiResponse  # type: ignore
    from ._models import Product  # type: ignore

from ._products_api_store_enums import (
    HostOptions,
)

__all__ = [
    'ApiResponse',
    'Product',
    'HostOptions',
]
